name: lynsok_core
description: Core library for Lynsok, providing essential functionalities and utilities for the Lynsok ecosystem.
version: 0.1.0

environment:
  sdk: ^3.10.4

resolution: workspace

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  archive: ^3.5.1
  synchronized: ^3.0.0
  shelf: ^1.4.2
  shelf_router: ^1.0.4
  http: ^1.6.0
  mcp_dart: ^2.1.0
# Add dev dependencies here.

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
